<!DOCTYPE html>
<html lang="en-GB">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <title><?= smart_quotes((isset($title) ? ($title . ' &mdash; ' . $this->site('title')) : $this->site('title'))); ?></title>

    <meta name="author" content="<?= (isset($author) ? $author : $this->site('author')); ?>>">
    <meta name="description" content="<?= (isset($extract) ? $extract : (isset($description) ? $description : $this->site('description'))) ?>" />
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="generator" content="tapestry.cloud"/>

    <link rel="canonical" href="<?= $this->getUrl() ?>" />
    <link rel="stylesheet" type="text/css" href="<?= $this->asset('css/main.css') ?>" />
    <link rel="shortcut icon" type="image/x-icon" href="<?= $this->url('img/favicon.ico') ?>"/>
</head>
<body>

<?= $this->section('content') ?>

<footer class="pv3 ph3 ph6-ns bg-near-black silver">
    <div class="mw9 center cf">
        <p class="w-100 w-50-l fl-ns lh-copy">
            Made with <span class="red">&#10084;</span> by <a href="https://www.photogabble.co.uk" class="link hover-red underline">Simon</a> &amp; <a href="https://www.hellodeborah.co.uk" class="link hover-red underline">Debbie</a> Dann.<br>
            Built with <a href="https://www.tapestry.cloud" class="link hover-red underline">Tapestry</a>
        </p>

        <p class="w-100 w-50-l fl-ns tr-ns lh-copy">
            &copy;2018 Dann Digital, MIT Licensed.<br>
            <a href="<?= $this->url('/cookie-policy') ?>" class="link hover-red underline">Cookie Policy</a>&mdash;<a href="<?= $this->url('/privacy-policy') ?>" class="link hover-red underline">GDPR/Privacy Policy</a>
        </p>
    </div>
</footer>

</body>
</html>