---
layout: default
---

<header class="w-100 pv2 bg-light-yellow black" style="background-image: none;">
    <div class="mw9 center">
        <a href="<?= $this->url('/') ?>">
            <img src="<?= $this->url('img/logo.png') ?>" alt="Dann Digital (Digital is within a speech bubble)" title="Dann Digital (Digital is within a speech bubble)" height="30">
        </a>
    </div>
</header>

<main>
    <section id="services" class="pt5 pb5 bg-near-white">
        <div class="mw9 center">
            <h2 class="normal">About</h2>
            <p>
                Hello world
            </p>
        </div>
    </section>
</main>