---
layout: default
---

<header class="w-100 pv4 pv7-l ph6-ns bg-silver black">
    <div class="mw9 center">
        <a href="<?= $this->url('/') ?>">
            <img src="<?= $this->url('img/logo.png') ?>" alt="Dann Digital (Digital is within a speech bubble)" title="Dann Digital (Digital is within a speech bubble)">
        </a>
        <h1 class="normal">
            Hi there, we are Simon &amp; Debbie.
        </h1>
        <h2 class="fw1">
            A multidisciplinary husband and wife team, with over 10 years <br> digital media experience. Based in Andover, Hampshire.
        </h2>
    </div>
    <nav class="mw9 center">
        Available to hire &mdash; <a href="<?= $this->url('about') ?>" class="link underline hover-black">About</a> &mdash; <a href="mailto:hello@dann.digital" class="link underline hover-black"><span aria-hidden="true">&#9993;</span> hello@dann.digital</a>
    </nav>
</header>
<main>

    <section class="pt5 pb5 bg-primary silver">
        <div class="mw9 center">
            <h1 class="f5 ttu tracked fw6 normal">General Services</h1>
            <p class="tracked">We have over a decade of experience in providing the following:</p>

            <section class="lh-copy">
                <div class="cf">
                    <article class="fl pv2 w-100 w-third-l pr4-l">
                        <h2 class="f5 f4-ns fw6 mb0">Website Development/Design</h2>
                        <p class="f6 f5-ns measure lh-copy mt0">
                            We can work with you to develop your website project from the drawing
                            board to the browser, or if you already have a template in mind we
                            can customise it to your needs.
                        </p>
                    </article>
                    <article class="pv2 fl w-100 w-third-l ph3-l">
                        <h2 class="f5 f4-ns fw6 mb0">Single Page Apps (SPAs)</h2>
                        <p class="f6 f5-ns measure lh-copy mt0">
                            From basic digital brochures (iDetails) designed to run within a tablet at a stand during a conference
                            to large multi&ndash;user online applications, we have the experience to help guide your project to success.
                        </p>
                    </article>
                    <article class="pv2 fl w-100 w-third-l pl4-l">
                        <h2 class="f5 f4-ns  fw6 mb0">
                            eCommerce solutions
                        </h2>
                        <p class="f6 f5-ns measure lh-copy mt0">
                            Do you have an online shop that you feel could be performing better? Or are you a shop owner wanting to find out
                            how to begin selling online? We can provide both consultation and bespoke eCommerce roll out depending on your needs.
                        </p>
                    </article>
                </div>
                <div class="cf w-100">
                    <article class="pv2 fl w-100 w-third-l pl0 pr4-l">
                        <h2 class="f5 f4-ns fw6 mb0">PSD to HTML</h2>
                        <p class="f6 f5-ns measure lh-copy mt0">
                            From PhotoShop to web page as fast as possible. We provide standard packages with up to next day turn around on
                            converting PhotoShop templates to static HTML.
                        </p>
                    </article>
                    <article class="pv2 fl w-100 w-third-l ph3-l">
                        <h2 class="f5 f4-ns  fw6 mb0">Social Media Strategy</h2>
                        <p class="f6 f5-ns measure lh-copy mt0">
                            Do you want to identify where your social is going wrong? Interested in increasing performance? If so get in touch.
                        </p>
                    </article>
                    <article class="pv2 fl w-100 w-third-l pl4-l">
                        <h2 class="f5 f4-ns fw6 mb0">
                            Brand Consultancy
                        </h2>
                        <p class="f6 f5-ns measure lh-copy mt0">

                        </p>
                    </article>
                </div>
            </section>
        </div>
    </section>

    <?php /*

    <section id="services" class="pt5 pb5">
        <div class="mw9 center">
            <h2 class="normal">General Services</h2>

            <div class="bg-near-white pa4">
                <h2 class="normal">Website Development/Design</h2>
                <p>Allow us to provide over a decade of experience in website development</p>
            </div>

            <a href="#" class="link">Website Development/Design</a> &ndash; <a href="#" class="link">Single Page Apps (SPA)</a> &ndash; <a href="#" class="link">eCommerce</a> &ndash; <a href="#" class="link">Social Media Strategy</a>
        </div>
    </section>

    <section class="pt5 pb5 bg-primary light-yellow">
        <div class="mw9 center">
            <h2 class="normal">Section Heading</h2>
            <p class="">Hello world!</p>
        </div>
    </section>

    <section id="map" class="pt5 pb5 bg-near-black light-yellow">
        <div class="mw9 center">
            <p>Hello world!</p>
        </div>
    </section>
    */ ?>
</main>